image: node:10.16.3

stages:
  - test
  - build

# "Dependency Audit":
#   stage: test
#   script:
#     - npm audit --level high

"Script Linting":
  stage: test
  script:
    - npm ci
    - npm run lint

pages:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
