image: node:10.16.1

stages:
  - test
  - build

"Dependency Audit":
  stage: test
  script:
    - npm audit --audit-level=high

Linting:
  stage: test
  script:
    - npm ci
    - npm run lint

pages:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
