name: Publish Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Assets
    runs-on: node:10.16.3-apline
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
