name: Publish Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Assets
    runs-on: node:10.16.3-apline
    steps:
      - uses: actions/checkout@v1
      - run: npm ci && npm run build
